CREATE DATABASE franceamusee;
use franceamusee;

-- drop permet de supprimer toutes les tables initiée
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE if EXISTS REGION;
DROP TABLE if EXISTS DEPARTEMENT;
DROP TABLE if EXISTS MUSEE;
DROP TABLE if EXISTS MUSEE_VIRTUEL;
DROP TABLE if EXISTS EXPOSITION;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE REGION(
        ID    Int  Auto_increment  NOT NULL ,
        NOM   Varchar (100) NOT NULL ,
        PHOTO Varchar (255) NOT NULL
	,CONSTRAINT REGION_PK PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE DEPARTEMENT(
        ID        Int  Auto_increment  NOT NULL ,
        NOM       Varchar (255) NOT NULL ,
        NUMERO    Int NOT NULL ,
        PHOTO     Varchar (255) ,
        ID_REGION Int
	,CONSTRAINT DEPARTEMENT_PK PRIMARY KEY (ID)

	,CONSTRAINT DEPARTEMENT_REGION_FK FOREIGN KEY (ID_REGION) REFERENCES REGION(ID)
)ENGINE=InnoDB;

CREATE TABLE MUSEE(
        ID             Int  Auto_increment  NOT NULL ,
        NOM            Varchar (255) NOT NULL ,
        ADRESSE        Varchar (255) NOT NULL ,
        VILLE          Varchar (255) NOT NULL ,
        CP             Varchar (25) NOT NULL ,
        TELEPHONE      Varchar (15) NOT NULL ,
        EMAIL          Varchar (50) NOT NULL ,
        SITE           Varchar (75) NOT NULL ,
        DESCRIPTION    Text NOT NULL ,
        ID_DEPARTEMENT Int
	,CONSTRAINT MUSEE_PK PRIMARY KEY (ID)

	,CONSTRAINT MUSEE_DEPARTEMENT_FK FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID)
)ENGINE=InnoDB;

CREATE TABLE EXPOSITION(
        ID          Int  Auto_increment  NOT NULL ,
        NOM         Varchar (255) NOT NULL ,
        DATE        Datetime NOT NULL ,
        DESCRIPTION Text NOT NULL ,
        ID_MUSEE    Int
	,CONSTRAINT EXPOSITION_PK PRIMARY KEY (ID)

	,CONSTRAINT EXPOSITION_MUSEE_FK FOREIGN KEY (ID_MUSEE) REFERENCES MUSEE(ID)
)ENGINE=InnoDB;


CREATE TABLE MUSEE_VIRTUEL(
        ID          Int  Auto_increment  NOT NULL ,
        DESCRIPTION Text NOT NULL ,
        ID_MUSEE    Int NOT NULL
	,CONSTRAINT MUSEE_VIRTUEL_PK PRIMARY KEY (ID)

	,CONSTRAINT MUSEE_VIRTUEL_MUSEE_FK FOREIGN KEY (ID_MUSEE) REFERENCES MUSEE(ID)
	,CONSTRAINT MUSEE_VIRTUEL_MUSEE_AK UNIQUE (ID_MUSEE)
)ENGINE=InnoDB;



